# ./github/workflows/assign-reviewers.yml
# Note: These reviewers would only be accessible only when the repository is public or has github enterprise plan
name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Team and Persons"
        uses: rowi1de/auto-assign-review-teams@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org: "Next-Corner" #only needed for  pick-one-from-persons-or-team=true
          teams: "Developers" # only works for GitHub Organisation/Teams
          persons: "RealHenryMartinez, RalphAnthonyLopez" # add individual persons here
          include-draft: false # Draft PRs will be skipped (default: false)
          skip-with-manual-reviewers: 1 # Skip this action, if the number of reviwers was already assigned (default: 0)
          pick-one-from-persons-or-team: false # Will pick out one reviewer from persons and/or the first GitHub team and "org" set (default: false)